const BUILTIN_TEMPLATES = [
  {
    id: 'classic-gradient-spotlight',
    slug: 'classic-gradient-spotlight',
    name: 'Classic Gradient Spotlight',
    description: 'Balanced hero layout with a soft gradient backdrop and centered messaging.',
    version: '1.0.0',
    status: 'PUBLISHED',
    isDefault: true,
    tags: ['balanced', 'gradient', 'spotlight'],
    supportedDevices: ['iPhone', 'iPad'],
    aspectRatios: ['9:19.5', '3:4'],
    thumbnailUrl: null,
    schema: {
      metadata: {
        label: 'Classic Gradient Spotlight',
        version: '1.0.0',
      },
      canvas: {
        defaultDevice: 'iPhone',
        devices: {
          iPhone: {
            width: 1284,
            height: 2778,
            safeArea: { top: 160, right: 120, bottom: 220, left: 120 },
            background: {
              type: 'gradient',
              direction: 'vertical',
              stops: [
                { offset: 0, color: 'accentLighten(62)' },
                { offset: 1, color: '#f7f8ff' },
              ],
            },
          },
          iPad: {
            width: 2048,
            height: 2732,
            safeArea: { top: 200, right: 200, bottom: 280, left: 200 },
            background: {
              type: 'gradient',
              direction: 'vertical',
              stops: [
                { offset: 0, color: 'accentLighten(58)' },
                { offset: 1, color: '#fdfdfd' },
              ],
            },
          },
        },
      },
      layers: [
        {
          type: 'heading',
          textSource: 'heading',
          position: { x: 0.5, y: 0.17 },
          maxWidthRatio: 0.78,
          font: {
            family: '{{headingFont}}',
            weight: '700',
            size: 120,
          },
          color: '#0f172a',
          lineHeight: 1.05,
          allowOffset: true,
        },
        {
          type: 'subheading',
          textSource: 'subheading',
          position: { x: 0.5, y: 0.30 },
          maxWidthRatio: 0.74,
          font: {
            family: '{{subheadingFont}}',
            weight: '400',
            size: 72,
          },
          color: '#334155',
          lineHeight: 1.2,
          allowOffset: true,
        },
        {
          type: 'accentShape',
          shape: 'rounded-rect',
          position: { x: 0.5, y: 0.67 },
          size: { widthRatio: 0.92, heightRatio: 0.54 },
          color: 'accentLighten(48)',
          opacity: 0.38,
          cornerRadiusRatio: 0.12,
          blur: 65,
        },
        {
          type: 'mockup',
          position: { x: 0.5, y: 0.66 },
          size: { scale: 0.88, maxWidthRatio: 0.85, maxHeightRatio: 0.64 },
          shadow: {
            blur: 90,
            color: 'rgba(15, 23, 42, 0.25)',
            offsetX: 0,
            offsetY: 38,
          },
          allowOffset: true,
        },
      ],
    },
  },
  {
    id: 'bold-split-perspective',
    slug: 'bold-split-perspective',
    name: 'Bold Split Perspective',
    description: 'Editorial split layout with left-aligned storytelling and elevated device framing.',
    version: '1.0.0',
    status: 'PUBLISHED',
    isDefault: false,
    tags: ['split', 'editorial', 'bold'],
    supportedDevices: ['iPhone', 'iPad'],
    aspectRatios: ['9:19.5', '3:4'],
    thumbnailUrl: null,
    schema: {
      metadata: {
        label: 'Bold Split Perspective',
        version: '1.0.0',
      },
      canvas: {
        defaultDevice: 'iPhone',
        devices: {
          iPhone: {
            width: 1284,
            height: 2778,
            safeArea: { top: 180, right: 140, bottom: 240, left: 140 },
            background: {
              type: 'gradient',
              direction: 'diagonal-bottom-left',
              stops: [
                { offset: 0, color: '#0f172a' },
                { offset: 1, color: 'accentLighten(32)' },
              ],
            },
          },
          iPad: {
            width: 2048,
            height: 2732,
            safeArea: { top: 200, right: 220, bottom: 300, left: 220 },
            background: {
              type: 'gradient',
              direction: 'horizontal',
              stops: [
                { offset: 0, color: '#111827' },
                { offset: 1, color: 'accentLighten(24)' },
              ],
            },
          },
        },
      },
      layers: [
        {
          type: 'accentShape',
          shape: 'rounded-rect',
          position: { x: 0.3, y: 0.58 },
          size: { widthRatio: 0.42, heightRatio: 0.65 },
          color: 'rgba(15, 23, 42, 0.55)',
          cornerRadiusRatio: 0.22,
          blur: 120,
        },
        {
          type: 'accentShape',
          shape: 'circle',
          position: { x: 0.82, y: 0.18 },
          size: { widthRatio: 0.16 },
          color: 'accentLighten(46)',
          opacity: 0.55,
          blur: 65,
        },
        {
          type: 'heading',
          textSource: 'heading',
          position: { x: 0.26, y: 0.26 },
          maxWidthRatio: 0.44,
          font: {
            family: '{{headingFont}}',
            weight: '800',
            size: 118,
            transform: 'uppercase',
          },
          color: '#f8fafc',
          lineHeight: 1.08,
          textAlign: 'left',
          allowOffset: true,
        },
        {
          type: 'subheading',
          textSource: 'subheading',
          position: { x: 0.26, y: 0.42 },
          maxWidthRatio: 0.42,
          font: {
            family: '{{subheadingFont}}',
            weight: '400',
            size: 64,
          },
          color: 'rgba(226, 232, 240, 0.86)',
          lineHeight: 1.35,
          textAlign: 'left',
          allowOffset: true,
        },
        {
          type: 'badge',
          text: 'App Store Editors’ Choice',
          position: { x: 0.26, y: 0.58 },
          padding: { x: 32, y: 16 },
          color: '#0f172a',
          backgroundColor: 'accentLighten(50)',
          borderRadius: 32,
          font: {
            family: 'Inter',
            weight: '600',
            size: 36,
            letterSpacing: 1.2,
          },
        },
        {
          type: 'mockup',
          position: { x: 0.68, y: 0.6 },
          size: { scale: 0.9, maxWidthRatio: 0.64, maxHeightRatio: 0.72 },
          rotation: -8,
          shadow: {
            blur: 120,
            color: 'rgba(14, 116, 144, 0.45)',
            offsetX: 0,
            offsetY: 54,
          },
          allowOffset: true,
        },
      ],
    },
  },
  {
    id: 'nocturne-neon-flow',
    slug: 'nocturne-neon-flow',
    name: 'Nocturne Neon Flow',
    description: 'Immersive night-mode layout with neon gradients and flowing light trails.',
    version: '1.0.0',
    status: 'PUBLISHED',
    isDefault: false,
    tags: ['dark mode', 'neon', 'immersive'],
    supportedDevices: ['iPhone', 'iPad'],
    aspectRatios: ['9:19.5', '3:4'],
    thumbnailUrl: null,
    schema: {
      metadata: {
        label: 'Nocturne Neon Flow',
        version: '1.0.0',
      },
      canvas: {
        defaultDevice: 'iPhone',
        devices: {
          iPhone: {
            width: 1284,
            height: 2778,
            safeArea: { top: 200, right: 140, bottom: 260, left: 140 },
            background: {
              type: 'gradient',
              direction: 'radial',
              stops: [
                { offset: 0, color: '#0b1120' },
                { offset: 0.45, color: '#0f172a' },
                { offset: 1, color: '#020617' },
              ],
            },
          },
          iPad: {
            width: 2048,
            height: 2732,
            safeArea: { top: 240, right: 220, bottom: 320, left: 220 },
            background: {
              type: 'gradient',
              direction: 'radial',
              stops: [
                { offset: 0, color: '#020617' },
                { offset: 0.5, color: '#0b1120' },
                { offset: 1, color: '#020617' },
              ],
            },
          },
        },
      },
      layers: [
        {
          type: 'accentShape',
          shape: 'capsule',
          position: { x: 0.5, y: 0.25 },
          size: { widthRatio: 0.72, heightRatio: 0.08 },
          color: 'rgba(56, 189, 248, 0.35)',
          blur: 160,
        },
        {
          type: 'accentShape',
          shape: 'capsule',
          position: { x: 0.65, y: 0.72 },
          size: { widthRatio: 0.48, heightRatio: 0.06 },
          color: 'rgba(129, 140, 248, 0.32)',
          blur: 120,
          rotation: -22,
        },
        {
          type: 'heading',
          textSource: 'heading',
          position: { x: 0.5, y: 0.2 },
          maxWidthRatio: 0.74,
          font: {
            family: '{{headingFont}}',
            weight: '700',
            size: 124,
          },
          color: '#f8fafc',
          lineHeight: 1.1,
          textAlign: 'center',
          shadow: {
            blur: 36,
            color: 'rgba(59, 130, 246, 0.35)',
            offsetX: 0,
            offsetY: 18,
          },
          allowOffset: true,
        },
        {
          type: 'subheading',
          textSource: 'subheading',
          position: { x: 0.5, y: 0.33 },
          maxWidthRatio: 0.68,
          font: {
            family: '{{subheadingFont}}',
            weight: '400',
            size: 70,
          },
          color: 'rgba(148, 163, 184, 0.9)',
          lineHeight: 1.35,
          textAlign: 'center',
          allowOffset: true,
        },
        {
          type: 'badge',
          text: 'Immersive AR Experience',
          position: { x: 0.5, y: 0.42 },
          padding: { x: 36, y: 18 },
          color: '#020617',
          backgroundColor: 'accentLighten(52)',
          borderRadius: 999,
          opacity: 0.9,
          font: {
            family: 'Inter',
            weight: '600',
            size: 34,
            letterSpacing: 1.5,
          },
        },
        {
          type: 'mockup',
          position: { x: 0.5, y: 0.7 },
          size: { scale: 0.92, maxWidthRatio: 0.8, maxHeightRatio: 0.68 },
          shadow: {
            blur: 140,
            color: 'rgba(14, 165, 233, 0.42)',
            offsetX: 0,
            offsetY: 62,
          },
          allowOffset: true,
        },
      ],
    },
  },
];

module.exports = {
  BUILTIN_TEMPLATES,
};
